# Generated by Django 5.1.2 on 2025-01-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один вариант ответа'), ('multiple', 'Несколько вариантов ответа'), ('text', 'Текстовый ответ')], default='single', max_length=10),
        ),
    ]
