version: '1.0'
name: currency-converter

container:
  image: cr.yandex/crpkr28qghq16h1feno9/currency-converter:v1
  resources:
    memory: 256MB
    cores: 1
  concurrency: 8
  env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: CONVERTER_PORT
      value: "8080"
    - name: ANALYTICS_PORT
      value: "8081"